### PR TITLE
 Replace rospack usage with ament_index_python 

### PR DESCRIPTION
**Pull request by jacobperron**

### CODE REVIEW

**Comment by jacobperron** [comment]
In retrospect, I think we might want to use `get_package_share_directory()` instead of `get_package_prefix()` for substitution, which would turn common substitutions like

        $(find foo)/share/foo/urdf/my_file.xml

into 

        $(find foo)/urdf/my_file.xml

Even better, we might also want to provide multiple find options for the package root and share directory (similar to launch https://github.com/ros2/launch_ros/pull/57). For example,

        $(find-share foo)/urdf/my_file.xml

        $(find-prefix foo)/some/path/to/my.xml

**Comment by IanTheEngineer** [comment]
@jacobperron - I would advocate for keeping the `$(find foo)` to avoid breaking old Xacros and URDF's. Otherwise it could turn into "another" step to port to ROS2.

I do agree with you though, `xacro` should be flexible or smart enough to look in the share or prefix path.

**Comment by IanTheEngineer** [comment]
@jacobperron, @gonzodepedro, & @clalancette after a bit more consideration this weekend, I still believe we should keep the `$(find foo)` syntax intact from ROS1 Xacro. 

I also think the `find` feature should at least be consistent with how RViz2 finds meshes in its `package://my_pkg_description/meshes/my_mesh.stl` syntax operates:

 **using the get_package_share_directory()** functionality to find the <br/>`install/my_pkg_description/share/my_pkg_description/` directory to find both `xacro`/`urdf` files and meshes alike.

**Comment by jacobperron** [comment]
Closing in favor of https://github.com/ros/xacro/pull/211.

I suggest any further discussion about the `find` substitution happen there.

**Pull request closed without merging**
